### ISSUE TITLE
Suggesting a style update: Adding a back button in the reflection 

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#100]
**Screenshot**
Please provide a screenshot of the current interface where you would like the styling update.
<img width="1274" alt="image" src="https://github.com/cherryontech/Uncloud/assets/163033562/b55531ae-d4ee-4118-84d8-596f2b8f3dcf">

**Describe the Requested Styling Update**
There should be back button.

**Relevant Wireframe**
If relevant, provide a link to any wireframes/design specs we may have missed, or which may be helpful for implementing the style update.

Scrum 21

**Additional context**
Add any other information here.

**Comment by GinaCastromonte** [comment]
<img width="1485" alt="Screenshot 2024-06-14 at 6 15 48 PM" src="https://github.com/cherryontech/Uncloud/assets/123599985/bbd86a8b-5f47-4177-af8a-9d4a90541fad">
