### ISSUE TITLE
Suggesting a style update: Calendar date selection update

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#101]
**Screenshot**
Please provide a screenshot of the current interface where you would like the styling update.

<img width="209" alt="image" src="https://github.com/cherryontech/Uncloud/assets/163033562/72cfeab5-89fa-48b8-97b5-f6272a88d196">

**Describe the Requested Styling Update**
Today's date should always have the primary blue circle button with the date and this blue color doesn't change. 
The selected date should be the little blue circle with the primary blue text. ( Like the mini calendar). 

**Relevant Wireframe**
If relevant, provide a link to any wireframes/design specs we may have missed, or which may be helpful for implementing the style update.

**Additional context**
Add any other information here.

**Comment by GinaCastromonte** [comment]
<img width="774" alt="Screenshot 2024-06-14 at 6 18 31 PM" src="https://github.com/cherryontech/Uncloud/assets/123599985/8754bc85-59d6-45b4-a817-804ea6640631">
