### ISSUE TITLE
Suggesting a style update: Applying the same hover and selection state

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#104]
**Screenshot**
Please provide a screenshot of the current interface where you would like the styling update.
<img width="491" alt="image" src="https://github.com/cherryontech/Uncloud/assets/163033562/1a82898d-346d-414a-9e30-f660a8783240">

**Describe the Requested Styling Update**
When the user is hovering, the stroke around the box should be the primary blue, and when the box is selected it should have the same primary blue with light blue around it. 

**Relevant Wireframe**
If relevant, provide a link to any wireframes/design specs we may have missed, or which may be helpful for implementing the style update.

**Additional context**
Add any other information here.

**Comment by paola4** [comment]
Implemented in latest PR.
