### ISSUE TITLE
Box size adjustment

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#105]
**Screenshot**
Please provide a screenshot of the current interface where you would like the styling update.
<img width="944" alt="image" src="https://github.com/cherryontech/Uncloud/assets/163033562/225139d7-241f-4b60-8abe-1131c0293c0c">

**Describe the Requested Styling Update**
The text should be within the box

**Relevant Wireframe**
If relevant, provide a link to any wireframes/design specs we may have missed, or which may be helpful for implementing the style update.

**Additional context**
I am using a windows computer (Browser: Chrome)

**Comment by GinaCastromonte** [comment]
Hey Katie, what size screen/ browser are you using?

**Comment by Katiechoi** [comment]
I'm using a windows (chrome) computer and the screen size is 1920 x 1200

**Comment by paola4** [comment]
Fixed in latest PR.
