### ISSUE TITLE
Suggesting a style update: Mini Calendar change from Month to Year. 

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#40]
**Screenshot**
<img width="212" alt="image" src="https://github.com/cherryontech/jupiter-jumpers/assets/163033562/18122678-fca4-4eb6-a692-161e770fc4c0">

**Describe the Requested Styling Update**
When you click on the Month of the year of the Mini calendar, year calendar replaces the month calendar. Not one on top of another. 

**Relevant Wireframe**
Downdown (on the right side of Scrum 29). 

**Additional context**
The prototype works if you need extra visual information.

**Comment by paola4** [comment]
Addressed in [PR 47](https://github.com/cherryontech/jupiter-jumpers/pull/47).
