### ISSUE TITLE
Bug: Mini Calendar and Big calendar interaction. 

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#42]
**Describe the bug**

When I change the month on the mini calendar, Big calendar changes with it. 

**To Reproduce**

1. Go to Mini calendar
2. Click on either chevrons 

**Expected behavior**

when the user change the month in the mini calendar, Big calendar shouldn't change until the user selects a specific date on the mini calendar. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Failure Logs**
Please include any relevant log snippets or files here.

**Additional context**

**Comment by paola4** [comment]
Addressed in [PR 47](https://github.com/cherryontech/jupiter-jumpers/pull/47).
