### ISSUE TITLE
Suggesting a style update: Mini Calendar Date and Year Update

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#43]
**Screenshot**
<img width="237" alt="image" src="https://github.com/cherryontech/jupiter-jumpers/assets/163033562/be918a47-7e95-426e-8bd9-80785b2630f6">

**Describe the Requested Styling Update**
The date and month should be on the same line for all the months. 

**Relevant Wireframe**
If relevant, provide a link to any wireframes/design specs we may have missed, or which may be helpful for implementing the style update.

**Additional context**
Add any other information here.

**Comment by paola4** [comment]
Addressed in [PR 47](https://github.com/cherryontech/jupiter-jumpers/pull/47).
