### ISSUE TITLE
Suggesting a style update: Today's date and Selection date on mini calendar. 

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#44]
**Screenshot**
<img width="224" alt="image" src="https://github.com/cherryontech/jupiter-jumpers/assets/163033562/b3748002-a283-4f78-8a71-9552e4cfe203">

Please provide a screenshot of the current interface where you would like the styling update.

**Describe the Requested Styling Update**
Like the picture, only today's date should be dark blue with white numbers and the selected date should be light blue with blue lettering.  And the lettering should be semibold for today's date and when the day is selected.

**Relevant Wireframe**
Scrum 30 ( Mini Calendar day selected)

**Additional context**
Add any other information here.

**Comment by paola4** [comment]
Addressed in [PR 47](https://github.com/cherryontech/jupiter-jumpers/pull/47).
