### ISSUE TITLE
Bug: Summary page to Daily view page

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#45]
**Describe the bug**

From the summary page, when i click on the chevron, it doesn't take me to that day's daily view.

**To Reproduce**

1. Go to 'summary page'
2. Click on 'one of the collapsed daily log'

**Expected behavior**

When you click on a collapsed log, it should take you to the detailed daily log page. 

**Screenshots**
<img width="434" alt="image" src="https://github.com/cherryontech/jupiter-jumpers/assets/163033562/9f0029d8-8d9f-4e5f-970e-d1cb24ec7b9a">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Failure Logs**
Please include any relevant log snippets or files here.

**Additional context**

**Comment by paola4** [comment]
Addressed in PR 46: https://github.com/cherryontech/jupiter-jumpers/pull/46

**Here is the URL with the fix:** https://deploy-preview-46--uncloud.netlify.app/

Does this fix the issue? If not, let me know! If so, I'll close this issue :).
