### ISSUE TITLE
Suggesting a style update: Welcome Page

### ISSUE THREAD

**Issue by Vannikumari** [cherryontech/jupiter-jumpers#50]
**Screenshot**
<img width="855" alt="Screenshot 2024-05-23 at 11 47 25 AM" src="https://github.com/cherryontech/jupiter-jumpers/assets/167365108/2753e745-3ec7-464d-94a0-619ea9ad3621">

**Describe the Requested Styling Update**
1) I feel "Welcome in Vanni Sinha" in one line would look more appropriate with an "!" mark. If the full name won't fit in one line we can display only the first name on the welcome page. For example "Welcome in Vanni!" 

2) There is a line missing in between the paragraphs.  

**Relevant Wireframe**
Please check the sample wireframe in Figma 

**Additional context**
Non

**Comment by paola4** [comment]
Addressed in [PR 55](https://github.com/cherryontech/jupiter-jumpers/pull/55). Deployment URL here: https://deploy-preview-55--uncloud.netlify.app/.
