### ISSUE TITLE
Feature: As a user, I want the "drop-down menu to disappear when I click anywhere on the screen" so that "I can easily return to the dashboard.

### ISSUE THREAD

**Issue by Vannikumari** [cherryontech/jupiter-jumpers#51]
**User Story**
What is the relevant user story? e.g., As a user, I want [some goal] so that [some reason].
<img width="447" alt="Screenshot 2024-05-23 at 12 09 14 PM" src="https://github.com/cherryontech/jupiter-jumpers/assets/167365108/01b87f49-db32-4bee-b4f7-69d23c3c2ba2">

As a user, I want the "drop-down menu to disappear when I click anywhere on the screen" so that "I can easily return to the dashboard.

**Describe the feature**
Having both features—making the drop-down menu disappear by clicking anywhere on the dashboard or by clicking the "^" sign—would be more user-friendly.

**Acceptance Criteria**
N/A

**Additional context**
N/A

**Comment by paola4** [comment]
Addressed in [PR 55](https://github.com/cherryontech/jupiter-jumpers/pull/55). Deployment URL here: https://deploy-preview-55--uncloud.netlify.app/.
