### ISSUE TITLE
Suggesting a style update : blue circle for the date in large calendar. 

### ISSUE THREAD

**Issue by Vannikumari** [cherryontech/jupiter-jumpers#52]
**Screenshot**
<img width="536" alt="Screenshot 2024-05-23 at 12 29 54 PM" src="https://github.com/cherryontech/jupiter-jumpers/assets/167365108/d35e8013-fa27-4959-82a2-5e686be0cd33">

**Describe the Requested Styling Update**
The blue mark for the date should be a circle (not an oval shape.)

**Relevant Wireframe**
Wireframe in Figma 

**Additional context**
N/A

**Comment by paola4** [comment]
Addressed in [PR 55](https://github.com/cherryontech/jupiter-jumpers/pull/55). Deployment URL here: https://deploy-preview-55--uncloud.netlify.app/.
