### ISSUE TITLE
Suggesting a style update:  Summary page

### ISSUE THREAD

**Issue by Vannikumari** [cherryontech/jupiter-jumpers#53]
**Screenshot**
<img width="495" alt="Screenshot 2024-05-23 at 12 51 19 PM" src="https://github.com/cherryontech/jupiter-jumpers/assets/167365108/aeff9367-0a2f-4c63-9b0e-c5c90b3dc1c6">

**Describe the Requested Styling Update**
1) The line beside the date disappears in the hover state. It should remain in white as shown in the wireframe. 
2) The length of the line should be a little bit more. 
3) The date number and font should be one size more. I am not sure, but it feels smaller than the Figma file. 
4) The arrow colour should change to blue in the hover state. 
5) The emoji should be in a white square box. 

**Relevant Wireframe**
Figma file

**Additional context**
N/A

**Comment by paola4** [comment]
Addressed in [PR 55](https://github.com/cherryontech/jupiter-jumpers/pull/55). Deployment URL here: https://deploy-preview-55--uncloud.netlify.app/.
