### ISSUE TITLE
Bug: Signup page extending to full screen 

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#58]
**Describe the bug**
Right now the signup page is extending to full screen.

**To Reproduce**

1. Go to 'home page'
2. Click on 'signup'

**Expected behavior**
 The White border box should be the same size as log in. 

**Screenshots**
<img width="958" alt="image" src="https://github.com/cherryontech/jupiter-jumpers/assets/163033562/51d8b8c4-5787-44ee-8144-f769f588a7c8">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Failure Logs**
Please include any relevant log snippets or files here.

**Additional context**

**Comment by paola4** [comment]
Good catch! It should be fixed now: https://deploy-preview-57--uncloud.netlify.app/auth/signUp
