### ISSUE TITLE
Suggesting a style update: Incorect email or password font should be smaller. 

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#59]
**Screenshot**
<img width="359" alt="image" src="https://github.com/cherryontech/jupiter-jumpers/assets/163033562/0a9a1b4e-311d-4fc6-ab02-66d838a7111f">

Please provide a screenshot of the current interface where you would like the styling update.

**Describe the Requested Styling Update**
"incorrect email or password." wording should be reduced down to size 12px.

**Relevant Wireframe**
If relevant, provide a link to any wireframes/design specs we may have missed, or which may be helpful for implementing the style update.

**Additional context**
Add any other information here.

**Comment by paola4** [comment]
Updated the text style to 12px in the latest PR: https://deploy-preview-57--uncloud.netlify.app/
