### ISSUE TITLE
Bug:  Reflection deletion

### ISSUE THREAD

**Issue by flowflow620** [cherryontech/jupiter-jumpers#84]
**Describe the bug**
When you create an additional reflection you are not given the option to delete it if generated on accident. This reflection still posts whether you add text in there or not. 
**To Reproduce**

1. Go to 'Add Log'
2. Click on 'A weather mood cloud'
3. Scroll down to 'Reflections "Add another reflection"'

**Expected behavior**
So I expected if I accidentally clicked add another reflection and I went back to the additional reflection I'd be given the option to delete that reflection.

**Screenshots**
![Screenshot 2024-06-08 10 54 33 AM](https://github.com/cherryontech/Uncloud/assets/169382564/68cf290b-a933-4980-ac5c-cde1cf9e3132)
**Desktop (please complete the following information):**

- Acer Chromebook 15

**Smartphone (please complete the following information):**

**Failure Logs**
Please include any relevant log snippets or files here.

**Additional context**

**Comment by paola4** [comment]
Fixed in latest PR.
