### ISSUE TITLE
Bug: Profile picture flicker

### ISSUE THREAD

**Issue by flowflow620** [cherryontech/jupiter-jumpers#86]
**Describe the bug**
After I uploaded a profile picture when I tested out adding information I the other cells my profile picture flickers while adding text into other fields
**To Reproduce**

1. Go to 'Profile'
2. Click on 'Choose Image'
3. Scroll down to 'Any of the test boxes and add text while a profile photo is in there '

**Expected behavior**
When I add text in any fields on the profile page while having a profile photo I expect my profile photo not to flicker 

**Screenshots**

**Desktop (please complete the following information):**

- Acer 15 Chromebook

**Smartphone (please complete the following information):**

**Failure Logs**
Please include any relevant log snippets or files here.

**Additional context**

**Comment by paola4** [comment]
Could not reproduce. If it persists or occurs again please re-create issue.
