### ISSUE TITLE
Feature: As a user, I want [some goal] so that [some reason].

### ISSUE THREAD

**Issue by Vannikumari** [cherryontech/jupiter-jumpers#91]
**User Story**
-
**Describe the feature**

The logo at the top left is not linked to the home page. The logo should be linked to the home page, as this provides an easy way for users to return to the home page if they get stuck on any other page while exploring the application.

**Acceptance Criteria**
-

**Additional context**
-

**Comment by GinaCastromonte** [comment]
This has been implemented now
