### ISSUE TITLE
Writing Update: Modify copy in Scrum 22 and Scrum 22 extended frame in figma.

### ISSUE THREAD

**Issue by lexcturner** [cherryontech/jupiter-jumpers#94]
**Screenshot**
Please provide a screenshot of the current UI to show where the change is needed.

![Screenshot (30)](https://github.com/cherryontech/Uncloud/assets/172082039/bdddf455-39cf-47ca-87f7-de2986221ee3)
![Screenshot (31)](https://github.com/cherryontech/Uncloud/assets/172082039/f4e2ee1e-bd1b-4ca0-a434-a2da175a41a0)

**Describe the required change**
A general description of what this feature should accomplish.

The 3 wins reflections description and Figma wireframe both have a lowercase 'u' at the beginning of a sentence. This should be capitalized to 'U'.  Also, the word 'details' is misspelled. I've attached images for reference. 

**Updated Copy**
What is the updated copy for this component?

Get specific! Use details to describe what you accomplished today.

**Additional context**
Add any other context or comments here.

**Comment by GinaCastromonte** [comment]
<img width="625" alt="Screenshot 2024-06-13 at 9 37 44 PM" src="https://github.com/cherryontech/Uncloud/assets/123599985/9d76a34a-b6a8-4936-8514-44b7817b9c4b">
