### ISSUE TITLE
Suggesting a style update: Logo in popup after getting started needs update

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#96]
**Screenshot**
Please provide a screenshot of the current interface where you would like the styling update.
<img width="504" alt="image" src="https://github.com/cherryontech/Uncloud/assets/163033562/75f545fa-a1e7-44b9-8346-2c0142427681">

**Describe the Requested Styling Update**
The icon right now is from mid-fidelity. It should be replaced with our logo. 

**Relevant Wireframe**
Scrum 12

**Additional context**
Add any other information here.

**Comment by GinaCastromonte** [comment]
![Screenshot 2024-06-13 at 9 35 17 PM](https://github.com/cherryontech/Uncloud/assets/123599985/2897aeda-e84d-4b9b-96c7-7a1b4b6ed763)
