### ISSUE TITLE
Suggesting a style update: Trends/ Filter should be open sans. 

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#97]
**Screenshot**
Please provide a screenshot of the current interface where you would like the styling update.
<img width="356" alt="image" src="https://github.com/cherryontech/Uncloud/assets/163033562/4dc25ca5-fdb5-4c3a-b0c5-7b6a4337b14b">

**Describe the Requested Styling Update**
A general description of what needs to be changed.
The font should be Open sans. 

**Relevant Wireframe**
If relevant, provide a link to any wireframes/design specs we may have missed, or which may be helpful for implementing the style update.

**Additional context**
Add any other information here.

**Comment by paola4** [comment]
I don't see this issue on my browser, but I removed a piece of code that I think could have been causing this. Double check and let me know if it's not resolved in the latest update.

**Comment by Katiechoi** [comment]
Yes it's still doing that on my end. I'm using windows
