### ISSUE TITLE
Writing Update: Modify copy in Mood log

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#98]
**Screenshot**
Please provide a screenshot of the current UI to show where the change is needed.
<img width="983" alt="image" src="https://github.com/cherryontech/Uncloud/assets/163033562/7b24f28a-1263-4ad9-8d75-1e81a78fa9ff">

**Describe the required change**
A general description of what this feature should accomplish.

Continue button should say continue to reflection. 
Done should say Done logging. 

**Updated Copy**
What is the updated copy for this component?

**Additional context**
Add any other context or comments here.

**Comment by GinaCastromonte** [comment]
![Screenshot 2024-06-13 at 9 15 01 PM](https://github.com/cherryontech/Uncloud/assets/123599985/765eacad-a163-4d6d-842d-291bc18ac84a)
