### ISSUE TITLE
Suggesting a style update: Reflection boxes need to be clickable not just the down carrot.

### ISSUE THREAD

**Issue by Katiechoi** [cherryontech/jupiter-jumpers#99]
**Screenshot**
Please provide a screenshot of the current interface where you would like the styling update.
<img width="584" alt="image" src="https://github.com/cherryontech/Uncloud/assets/163033562/3c21152e-721e-474c-a21a-4fa2a012f4a5">

**Describe the Requested Styling Update**
The whole wins of the day and reflection section should be clickable. 

**Relevant Wireframe**
If relevant, provide a link to any wireframes/design specs we may have missed, or which may be helpful for implementing the style update.

**Additional context**
Add any other information here.

**Comment by GinaCastromonte** [comment]
<img width="1002" alt="Screenshot 2024-06-14 at 6 17 08 PM" src="https://github.com/cherryontech/Uncloud/assets/123599985/1810e736-9a92-44b3-bd2e-22e054b4865b">
